/* FK DEL MODELO DE SERVICIOS */

ALTER TABLE ODS_HC_SERVICIOS MODIFY COLUMN ID_CLIENTE INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_serv_cli_idx (ID_CLIENTE ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_cli FOREIGN KEY (ID_CLIENTE)
	REFERENCES ODS.ODS_HC_CLIENTES (ID_CLIENTE);

ALTER TABLE ODS_HC_SERVICIOS MODIFY COLUMN ID_PRODUCT INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_serv_prod_idx (ID_PRODUCTO ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_prod FOREIGN KEY (ID_PRODUCTO)
	REFERENCES ODS.ODS_DM_PRODUCTOS (ID_PRODUCTO);

ALTER TABLE ODS_HC_SERVICIOS MODIFY COLUMN ID_CANAL INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_serv_canal_idx (ID_CANAL ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_canal FOREIGN KEY (ID_CANAL)
	REFERENCES ODS.ODS_DM_CANALES (ID_CANAL);

ALTER TABLE ODS_HC_SERVICIOS MODIFY COLUMN ID_DIRECCION_SERVICIO INT(10) UNSIGNED;	
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_serv_dirs_idx (ID_DIRECCION_SERVICIO ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_dirs FOREIGN KEY (ID_DIRECCION_SERVICIO)
	REFERENCES ODS.ODS_HC_DIRECCIONES (ID_DIRECCION_SERVICIO);
	
ALTER TABLE ODS_HC_CLIENTES MODIFY COLUMN ID_DIRECCION_CLIENTE INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_HC_CLIENTES ADD INDEX fk_cli_dirc_idx (ID_DIRECCION_CLIENTE ASC);
ALTER TABLE ODS.ODS_HC_CLIENTES ADD CONSTRAINT fk_cli_dirc FOREIGN KEY (ID_DIRECCION_CLIENTE)
	REFERENCES ODS.ODS_HC_DIRECCIONES;
		
ALTER TABLE ODS_HC_DIRECCIONES MODIFY COLUMN ID_CIUDAD_ESTADO INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_HC_DIRECCIONES ADD INDEX fk_dir_ciu_idx (ID_CIUDAD_ESTADO ASC);
ALTER TABLE ODS.ODS_HC_DIRECCIONES ADD CONSTRAINT fk_dir_ciu FOREIGN KEY (ID_CIUDAD_ESTADO ASC)
	REFERENCES ODS.ODS_DM_CIUDADES_ESTADO;
	
ALTER TABLE ODS_DM_CIUDADES_ESTADO MODIFY COLUMN ID_PAIS INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_DM_CIUDADES_ESTADO ADD INDEX fk_ciu_pais_idx (ID_PAIS ASC);
ALTER TABLE ODS.ODS_DM_CIUDADES_ESTADO ADD CONSTRAINT fk_ciu_pais FOREIGN KEY (ID_PAIS ASC)
	REFERENCES ODS.ODS_DM_PAISES;