/* FK DEL MODELO LLAMADAS */

ALTER TABLE ODS_HC_CLIENTES MODIFY COLUMN ID_CIENTE INT (10) UNSIGNED;
ALTER TABLE ODS_HC_CLIENTES ADD INDEX fk_cli_llam_idx (ID_CLIENTE ASC);
ALTER TABLE ODS.ODS_HC_CLIENTES ADD CONSTRAINT fk_cli_llam FOREIGN KEY (ID_CLIENTE)
	REFERENCES ODS.ODS_HC_LLAMADAS (ID_CLIENTE);

ALTER TABLE ODS_HC_LLAMADAS MODIFY COLUMN ID_DEPARTAMENTO_CC INT(10) UNSIGNED;
ALTER TABLE ODS_HC_LLAMADAS ADD INDEX fk_llam_dept_idx (ID_DEPARTAMENTO_CC ASC);
ALTER TABLE ODS_HC_LLAMADAS ADD CONSTRAINT fk_llam_dept FOREIGN KEY (ID_DEPARTAMENTO_CC)
	REFERENCES ODS.ODS_DM_DEPARTAMENTOS_CC (ID_DEPARTAMENTO_CC);
	
ALTER TABLE ODS_HC_LLAMADAS MODIFY COLUMN ID_AGENTE_CC INT(10) UNSIGNED;
ALTER TABLE ODS_HC_LLAMADAS ADD INDEX fk_llam_agen_idx (ID_AGENTE_CC ASC);
ALTER TABLE ODS_HC_LLAMADAS ADD CONSTRAINT fk_llam_agen FOREIGN KEY (ID_AGENTE_CC)
	REFERENCES ODS.ODS_DM_AGENTES_CC (ID_AGENTE_CC)
