/*Tablas:
	- ODS_HC_DIRECCIONES
	- ODS_HC_CLIENTES
	- ODS_DM_CIUDADES_ESTADOS
	- ODS_DM_PAISES
Ya pobladas en modelo clientes */


-- TABLA ODS_DM_CANALES

INSERT INTO ODS_DM_CANALES (DE_CANAL, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(CHANNEL)) DE_CANAL, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM
WHERE TRIM(CHANNEL)<>'';

INSERT INTO ODS_DM_CANALES VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_CANALES VALUES (98, 'NO APLICA', NOW(), NOW());

ANALYZE TABLE ODS_DM_CANALES;

-- TABLA ODS_HC_DIRECCIONES

INSERT INTO ODS_HC_DIRECCIONES (DE_DIRECCIONES, DE_CP, ID_CIUDAD_ESTADO, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(ADDRESS)) DIRECCION
, CASE WHEN LENGTH(TRIM(CLI.POSTAL_CODE))<>0 THEN TRIM(CLI.POSTAL_CODE) ELSE 99999 END CP, CIU.ID_CIUDAD_ESTADO, NOW(), NOW()
FROM STAGE.STG_CLIENTES_CRM CLI
INNER JOIN ODS.ODS_DM_PAISES PAI ON CASE WHEN LENGTH(TRIM(CLI.COUNTRY))<>0 THEN CLI.COUNTRY ELSE 'DESCONOCIDO' END=PAI.DE_PAIS
INNER JOIN ODS.ODS_DM_CIUDADES_ESTADOS CIU ON CASE WHEN LENGTH(TRIM(CLI.CITY))<>0 THEN CLI.CITY ELSE 'DESCONOCIDO' END=CIU.DE_CIUDAD
		AND CASE WHEN LENGTH(TRIM(CLI.STATE))<>0 THEN CLI.STATE ELSE 'DESCONOCIDO' END=CIU.DE_ESTADO
WHERE TRIM(ADDRESS)<>'';

INSERT INTO ODS_HC_DIRECCIONES VALUES (999999, 'DESCONODICO', 99999, 999, NOW(), NOW());
INSERT INTO ODS_HC_DIRECCIONES VALUES (999998, 'NO APLICA', 99998, 998, NOW(), NOW());

COMMIT;

ANALYZE TABLE ODS_HC_DIRECCIONES;

-- TABLA ODS_HM_SERVICIOS

USE ODS;

DROP TABLE IF EXISTS TMP_DIRECCIONES_SERVICIOS;

CREATE TABLE TMP_DIRECCIONES_SERVICIOS AS
SELECT DIR.ID_DIRECCION
, DIR.DE_DIRECCION
, DIR.DE_CP
, CIU.DE_CIUDAD
, CIU.DE_ESTADO
, PAI.DE_PAIS
FROM ODS.ODS_HC_DIRECCIONES DIR
INNER JOIN ODS.ODS_DM_CIUDADES_ESTADOS CIU ON DIR.ID_CIUDAD_ESTADO=CIU.ID_CIUDAD_ESTADO
INNER JOIN ODS.ODS_DM_PAISES PAI ON CIU.ID_PAIS=PAI.ID_PAIS;

DROP TABLE IF EXISTS TMP_DIRECCIONES_SERVICIOS2;

CREATE TABLE TMP_DIRECCIONES_SERVICIOS2 AS
SELECT CLIENTES.CUSTOMER_ID ID_CLIENTE
, DIR.ID_DIRECCION
FROM STAGE.STG_CLIENTES_CRM CLIENTES
INNER JOIN ODS.TMP_DIRECCIONES_SERVICIOS DIR
	ON CASE WHEN TRIM(ADDRESS)<>'' THEN UPPER(TRIM(CLIENTES.ADDRESS)) ELSE 'DESCONOCIDO' END=DIR.DE_DIRECCION
	AND CASE WHEN TRIM(CLIENTES.POSTAL_CODE)<>'' THEN TRIM(CLIENTES.POSTAL_CODE) ELSE 99999 END=DIR.DE_CP
    AND CASE WHEN TRIM(CLIENTES.CITY)<>'' THEN CLIENTES.CITY ELSE 'DESCONOCIDO' END=DIR.DE_CIUDAD
    AND CASE WHEN TRIM(CLIENTES.STATE)<>'' THEN CLIENTES.STATE ELSE 'DESCONOCIDO' END=DIR.DE_ESTADO
    AND CASE WHEN TRIM(CLIENTES.COUNTRY)<>'' THEN CLIENTES.COUNTRY ELSE 'DESCONOCIDO' END=DIR.DE_PAIS;

INSERT INTO ODS_HC_SERVICIOS	
SELECT A.PRODUCT_ID ID_SERVICIO
, A.CUSTOMER_ID ID_CLIENTE
, C.ID_PRODUCTO ID_PRODUCTO
, A.ACCESS_POINT PUNTO_ACCESO
, D.ID_CANAL ID_CANAL
, E.ID_AGENTE_CC ID_AGENTE
, CASE WHEN TRIM(DIR.ID_DIRECCION)<>'' THEN DIR.ID_DIRECCION ELSE 999999 END ID_DIRECCION
, CASE WHEN TRIM(A.START_DATE)<>'' THEN STR_TO_DATE(A.START_DATE, '%d/%m/%Y %H-%i-%s') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y %H-%i-%s') END FC_INICIO
, A.INSTALL_DATE FC_INSTALACION
, A.END_DATE FC_FIN
, NOW()
, STR_TO_DATE('31/12/9999','%d/%m/%Y')
FROM STAGE.STG_PRODUCTOS_CRM A 
INNER JOIN ODS_DM_PRODUCTOS C ON A.PRODUCT_NAME=C.DE_PRODUCTO
INNER JOIN ODS_DM_CANALES D ON A.CHANNEL=D.DE_CANAL
INNER JOIN ODS_DM_AGENTES_CC E 
	ON CASE WHEN TRIM(A.AGENT_CODE)<>'' THEN TRIM(A.AGENT_CODE) ELSE 9999 END=E.ID_AGENTE_CC
LEFT OUTER JOIN ODS.TMP_DIRECCIONES_SERVICIOS2 DIR ON DIR.ID_CLIENTE=A.CUSTOMER_ID;

COMMIT;

ANALYZE TABLE ODS_HC_SERVICIOS;

DROP TABLE IF EXISTS TMP_DIRECCIONES_SERVICIOS;
DROP TABLE IF EXISTS TMP_DIRECCIONES_SERVICIOS2;




